#!/usr/bin/env bash
prefix=""
fbin=""
if [[ -z $prefix ]]; then
   fc=$(readlink $0)
   if [[ -z $fc ]]; then
     fbin=$(dirname $0)
   else
     fbin=$(dirname $fc)
   fi
else
 fbin=$prefix/bin
fi
export PATH=$fbin:$PATH
"$fbin/fusioncatcher-batch.py" "$@"
